# Generated by Django 4.2.1 on 2023-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(max_length=20),
        ),
    ]
